# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TabNetModel": "00_core.ipynb",
         "nn.Module.size": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://mgrankin.github.io/fast_tabnet/"

git_url = "https://github.com/mgrankin/fast_tabnet/tree/master/"

def custom_doc_links(name): return None
